### ISSUE TITLE
binary weights?

### ISSUE THREAD

**Issue by yananliusdu** [eghouti/BinaryConnect#2]
Hi, thanks for your implementation of binary connect.

I don't know why but after running your project and readout all the weigths, it seems like they are not binary weights.

for example the kernel filter
          [ 0.4462, -0.4897,  0.3968, -0.8253],
          [ 0.8852,  0.3383,  0.6267, -0.2224],
          [ 0.2346, -0.4480, -0.5962, -0.7025]]],

is there something wrong with my turning ?

thanks.

**Comment by eghouti** [comment]
The code binarize weights, perforces training or test and then restores floating point weight. At which step did you print your weights? 
----- Mail d’origine -----
De: Yanan Liu <notifications@github.com>
À: eghouti/BinaryConnect <BinaryConnect@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Envoyé: Mon, 09 Dec 2019 16:59:46 +0100 (CET)
Objet: [eghouti/BinaryConnect] binary weights? (#2)

Hi, thanks for your implementation of binary connect.

I don't know why but after running your project and readout all the weigths, it seems like they are not binary weights.

for example the kernel filter
          [ 0.4462, -0.4897,  0.3968, -0.8253],
          [ 0.8852,  0.3383,  0.6267, -0.2224],
          [ 0.2346, -0.4480, -0.5962, -0.7025]]],

is there something wrong with my turning ?

thanks.

-- 
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/eghouti/BinaryConnect/issues/2

**Comment by yananliusdu** [comment]
Hi, thanks for your reply.

Actually, I print all the weights after training from model_best.pth.tar.  isn't is the final binary weights?

thanks.

**Comment by eghouti** [comment]
You can see in test function you banirize the weight, you perform the test then you restore the floating point and then you save the model, so if you want to get binary weight you need to load your model and then binarise weights using function bc.binarization

----- Mail original -----
De: "Yanan Liu" <notifications@github.com>
À: "eghouti/BinaryConnect" <BinaryConnect@noreply.github.com>
Cc: "Ghouthi BOUKLI HACENE" <ghouthi.bouklihacene@imt-atlantique.fr>, "Comment" <comment@noreply.github.com>
Envoyé: Mardi 10 Décembre 2019 05:16:08
Objet: Re: [eghouti/BinaryConnect] binary weights? (#2)

Hi, thanks for your reply.

Actually, I print all the weights after training from model_best.pth.tar.  isn't is the final binary weights?

thanks.

**Comment by SongFGH** [comment]
after line: bin_op.binarization(). You can input model.fc.weight, the output contain only 1 or -1.
after bin_op.restore(). You can input model.fc.weight, the output is float.
Good implementation of binary connect.
